"""initial schema

Revision ID: d7bbb1e63840
Revises: 
Create Date: 2026-03-09 16:22:15.895309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7bbb1e63840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('cost_factor', sa.Float(), nullable=False),
    sa.Column('speed_factor', sa.Float(), nullable=False),
    sa.Column('specialties', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_profile', sa.Text(), nullable=False),
    sa.Column('branding', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('architecture_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulated_clock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_advance_reason', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_role', sa.String(length=100), nullable=False),
    sa.Column('assigned_contractor', sa.String(length=255), nullable=True),
    sa.Column('facility', sa.String(length=255), nullable=True),
    sa.Column('prerequisites', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('nominal_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('simulated_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('simulated_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('rework_of', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['rework_of'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_artifacts')
    op.drop_table('tasks')
    op.drop_table('simulated_clock')
    op.drop_table('missions')
    op.drop_table('facilities')
    op.drop_table('contractors')
    # ### end Alembic commands ###
